import type { RoomSummary } from "@hotel-crm/shared/rooms";

export const initialRooms: RoomSummary[] = [
  {
    id: "room_101",
    number: "101",
    roomType: "Стандарт",
    unitKind: "room",
    status: "available",
    readiness: "clean",
    readinessLabel: "Готов",
    housekeepingNote: "Готов к заселению",
    nextAction: "Держать свободным для заездов",
    occupancyLabel: "Свободен сегодня",
    priority: "normal",
    floor: "1",
    zone: "Main",
    occupancyLimit: 2,
    amenities: ["wifi", "desk", "shower"],
    minibarEnabled: false,
    lastCleanedAt: "2026-03-25T09:10:00.000Z",
    nextArrivalLabel: "",
    outOfOrderReason: "",
    activeMaintenanceIncidentId: null,
    glampingMetadata: null
  },
  {
    id: "room_203",
    number: "203",
    roomType: "Двухместный",
    unitKind: "room",
    status: "dirty",
    readiness: "dirty",
    readinessLabel: "Грязный",
    housekeepingNote: "Гость выехал, нужна уборка",
    nextAction: "Начать уборку до заезда в 13:30",
    occupancyLabel: "Сегодня заезд",
    priority: "arrival_soon",
    floor: "2",
    zone: "Main",
    occupancyLimit: 2,
    amenities: ["wifi", "tv", "minibar"],
    minibarEnabled: true,
    lastCleanedAt: "2026-03-23T11:00:00.000Z",
    nextArrivalLabel: "Заезд до 13:30",
    outOfOrderReason: "",
    activeMaintenanceIncidentId: null,
    glampingMetadata: null
  },
  {
    id: "room_305",
    number: "305",
    roomType: "Семейный",
    unitKind: "room",
    status: "blocked_maintenance",
    readiness: "blocked",
    readinessLabel: "Заблокирован",
    housekeepingNote: "Сообщили о протечке в ванной",
    nextAction: "Держать в блоке до осмотра",
    occupancyLabel: "Недоступен",
    priority: "blocked",
    floor: "3",
    zone: "Family",
    occupancyLimit: 4,
    amenities: ["wifi", "crib", "kettle"],
    minibarEnabled: false,
    lastCleanedAt: "2026-03-22T09:30:00.000Z",
    nextArrivalLabel: "",
    outOfOrderReason: "Протечка в ванной",
    activeMaintenanceIncidentId: "maint_room_305",
    glampingMetadata: null
  }
];
